# Generated by Django 6.0 on 2026-01-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_unit_price_product_unit_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtrepayment",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.client",
            ),
        ),
    ]
